title: Latif Siddiq Sunny
description: Welcome to my personal site
google_analytics:
theme: jekyll-theme-hacker

social:
  name: Latif Siddiq Sunny
  links:
    - https://www.facebook.com/lsiddiqsunny
    - https://www.linkedin.com/in/lsiddiqsunny
    - https://github.com/lsiddiqsunny