title: Latif Siddiq Sunny
description: Welcome to my personal site
google_analytics:
theme: jekyll-theme-hacker

plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false