title: Latif Siddiq Sunny
email: lsiddiqsunny@gmail.com
description: My personal site
google_analytics:
theme: minima
github_username:  lsiddiqsunny
social:
  name: Latif Siddiq Sunny
  links:
    - https://www.facebook.com/lsiddiqsunny
    - https://www.linkedin.com/in/lsiddiqsunny
    - https://github.com/lsiddiqsunny
show_excerpts: true # set to false to remove excerpts on the homepage